import { CustomerClass } from './CustomerClass';
import { PermissionLevel } from './PermissionLevel';
export class ProfileInfo {
    companyName: string | null;
    companyCode: string | null;
    customerNo: string | null;
    terminalCode: string | null;
    distributor: string | null;
    distributorDepartment: string | null;
    basWare: boolean;
    punchOut: boolean;
    hookUrl: string | null;
    autoReplaceObsolete: boolean;
    ecoPctBasedOnWeight: boolean;
    name: string | null;
    username: string | null;
    email: string | null;
    noOfLines: number;
    consultant: string | null;
    activateAgreementFilter: boolean;
    activateApprovedSupplierFilter: boolean;
    siteId: number;
    shopType: number;
    keyAccountDescription: string | null;
    wishShop: boolean;
    caterShare: boolean;
    gmp: boolean;
    campaignPaper: boolean;
    logoPath: string | null;
    logoNodeId: number;
    isAdmin: boolean;
    postponeSurvey: boolean;
    showProcure: boolean;
    customerGroup: string | null;
    permissionLevel: PermissionLevel;
    chainName: string;
    isMemberOfSystemköp: boolean| false;
    customerClass: CustomerClass | null;
    excludeSurchargePct: boolean;
    depictModuleEnabled: boolean; 
    vendorNo: string;
}